# Generated by Django 2.2 on 2019-05-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=42, verbose_name='Titre')),
                ('content', models.TextField(null=True, verbose_name='Contenu')),
            ],
        ),
    ]
