# Generated by Django 2.2 on 2019-05-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigation1', '0002_clues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clues',
            new_name='Clue',
        ),
    ]
