# Generated by Django 2.2 on 2019-05-30 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigation1', '0003_auto_20190530_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigation1.Clue')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigation1.Profil')),
            ],
        ),
    ]
