# Generated by Django 2.2 on 2019-05-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation1', '0004_userclues'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='number',
            field=models.IntegerField(null=True, verbose_name='numéro'),
        ),
    ]
