# Generated by Django 2.2 on 2019-06-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation1', '0006_auto_20190530_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clue',
            name='content',
        ),
        migrations.AddField(
            model_name='clue',
            name='url_content',
            field=models.TextField(null=True, verbose_name='url_content'),
        ),
        migrations.AddField(
            model_name='clue',
            name='url_img_optionnel',
            field=models.TextField(null=True, verbose_name='url_img_optionnel'),
        ),
    ]
