# Generated by Django 2.2 on 2019-06-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation1', '0008_auto_20190601_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='url_content',
            field=models.URLField(null=True, verbose_name='url_content'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='url_img_optionnel',
            field=models.URLField(null=True, verbose_name='url_img_optionnel'),
        ),
    ]
