# Generated by Django 2.2 on 2019-06-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation1', '0009_auto_20190601_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clue',
            name='url_content',
        ),
        migrations.AlterField(
            model_name='clue',
            name='url_img_optionnel',
            field=models.CharField(default='rien', max_length=42, verbose_name='url_img_optionnel'),
        ),
    ]
