# Generated by Django 2.2 on 2019-06-05 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigation1', '0010_auto_20190601_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclues',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigation1.Profil'),
        ),
    ]
